Repository anoma/vscode-juvix, pull requests merged in 2023-05, with the labels that each got.

#64 Add html only sources task
  package.json
  src/judoc.ts
Labels: enhancement

#63 [#24] Support Multiline comments
  src/highlighting.ts
Labels: bug

#67 Fix incorrect goto properties parsing
  src/highlighting.ts
Labels: fix

#71 [#70] Use line comments instead of block by default
  language-configuration.json
Labels: enhancement

#74 Handle unicode character in semantic highlighting
  package.json
  src/highlighting.ts
Labels: syntax-highlighting

#75 Typecheck silently on every change
  package.json
  src/highlighting.ts
  src/tasks.ts
  test/HelloWorld.juvix
Labels: syntax-highlighting, typechecking

#78 Handle judoc as comments in highlighting
  src/highlighting.ts
Labels: syntax-highlighting

#81 Use the typecheckOn var from settings for deciding to typecheck
  src/check.ts
  test/Format.juvix
Labels: syntax-highlighting

#87 Fix some issues related to brackets
  language-configuration.json
Labels: enhancement, fix

#88 Display Type and documentation for Hovered Identifier
  juvix.version
  language-configuration.json
  src/definitions.ts
  src/extension.ts
  src/highlighting.ts
  src/hover.ts
  src/interfaces.ts
  src/judoc.ts
Labels: enhancement

#89 Add CodeLensProvider to insert module header
  package.json
  src/codelens.ts
  src/extension.ts
  src/highlighting.ts
  src/judoc.ts
  src/module.ts
  src/root.ts
  src/statusbar.ts
Labels: enhancement

#91 Fix documentation viewer
  src/config.ts
  src/extension.ts
  src/judoc.ts
  src/module.ts
  src/root.ts
Labels: fix

#93 Closes #52
  src/formatter.ts
Labels: fix
