Repository anoma/vscode-juvix, pull requests merged in 2023-04, with the labels that each got.

#56 Add in keyword to JuvixCore list
  syntaxes/JuvixCore.tmLanguage.json
  test/test.jvc
Labels: syntax-highlighting, juvix-bug

#58 Add Juvix version checking and other features
  .gitattributes
  .github/workflows/ci.yaml
  .gitignore
  .pre-commit-config.yaml
  .prettierignore
  .vscodeignore
  HACKING.md
  LICENSE
  Makefile
  juvix.version
  language-configuration.json
  package-lock.json
  package.json
  src/formatter.ts
  src/highlighting.ts
  src/juvixVersion.ts
  src/statusbar.ts
  src/tasks.ts
  syntaxes/JuvixCore.tmLanguage.json
  test/A.juvix
  test/B.juvix
  test/Format.juvix
  test/HelloWorld
  test/HelloWorld.juvix
  test/MidSquareHash.pir
  test/another.juvix
  test/identity.juvix
  test/range.pir
Labels: enhancement, maintenance

#59 remove juvix:format command in favor of using the built-in vsce api
  package-lock.json
  package.json
  src/tasks.ts
  test/HelloWorld.juvix
Labels: maintenance

#61 Fix tmp .juvix-build creation in run command
  src/config.ts
  src/tasks.ts
Labels: bug

#62 Allow multi-line error highlighting
  package.json
Labels: bug
