Repository anoma/vscode-juvix, pull requests merged in 2023-06, with the labels that each got.

#96 Apply new colour scheme from the Juvix doc
  package.json
  test/HelloWorld.juvix
Labels: syntax-highlighting

#101 Handle format command exit codes better
  src/formatter.ts
Labels: fix

#104 Fix grammar for comments
  syntaxes/Juvix.json
Labels: syntax-highlighting

#105 Use juvix-installer
  language-configuration.json
  package-lock.json
  package.json
  src/check.ts
  src/config.ts
  src/extension.ts
  src/installer.ts
  src/judoc.ts
  src/juvixVersion.ts
  src/repl.ts
  src/root.ts
  src/statusbar.ts
  src/utils/debug.ts
  syntaxes/Juvix.json
Labels: enhancement

#116 Clean up compile targets, remove old commands
  package.json
  src/config.ts
Labels: maintenance

#119 Set up tests on CI
  .github/workflows/ci.yaml
  package-lock.json
  src/codelens.ts
  src/definitions.ts
  src/hover.ts
  src/test/runTest.ts
  src/test/suite/extension.test.ts
  src/test/suite/index.ts
  src/utils/debug.ts
  test/suite/index.ts
Labels: test
